// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: cinema_orders_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the order item like ticket
type Status int32

const (
	// Awaiting payment, the next status after payment is PAID
	// or CANCELLED if the order was not paid within the specified period.
	Status_PAYMENT_REQUIRED Status = 0
	// The order is paid, after use, the status USED.
	// AFTER the buyer has requested a refund, the status switches to REFUND_AWAITING if the refund is approved
	// or remains PAID if the refund request is rejected.
	Status_PAID Status = 1
	// The order is awaiting a refund, after a successful refund, the order is awarded the REFUNDED status.
	Status_REFUND_AWAITING Status = 2
	// The order has been cancelled.
	Status_CANCELLED Status = 3
	// The order was fully completed, i.e. all the tickets was used and all the service was implemented.
	// After the buyer has requested a refund, the status switches to REFUND_AWAITING if the refund is approved
	// or remains USED if the refund request is rejected.
	Status_USED Status = 4
	// The funds for the order have been refunded.
	Status_REFUNDED Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PAYMENT_REQUIRED",
		1: "PAID",
		2: "REFUND_AWAITING",
		3: "CANCELLED",
		4: "USED",
		5: "REFUNDED",
	}
	Status_value = map[string]int32{
		"PAYMENT_REQUIRED": 0,
		"PAID":             1,
		"REFUND_AWAITING":  2,
		"CANCELLED":        3,
		"USED":             4,
		"REFUNDED":         5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cinema_orders_service_v1_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cinema_orders_service_v1_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

type Sort_Ordering int32

const (
	Sort_ASC  Sort_Ordering = 0
	Sort_DESC Sort_Ordering = 1
)

// Enum value maps for Sort_Ordering.
var (
	Sort_Ordering_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	Sort_Ordering_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x Sort_Ordering) Enum() *Sort_Ordering {
	p := new(Sort_Ordering)
	*p = x
	return p
}

func (x Sort_Ordering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort_Ordering) Descriptor() protoreflect.EnumDescriptor {
	return file_cinema_orders_service_v1_messages_proto_enumTypes[1].Descriptor()
}

func (Sort_Ordering) Type() protoreflect.EnumType {
	return &file_cinema_orders_service_v1_messages_proto_enumTypes[1]
}

func (x Sort_Ordering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort_Ordering.Descriptor instead.
func (Sort_Ordering) EnumDescriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{3, 0}
}

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time in format RFC3339, time must be in UTC
	// example: 2023-11-10T23:00:00Z
	FormattedTimestamp string `protobuf:"bytes,1,opt,name=formattedTimestamp,json=formatted_timestamp,proto3" json:"formattedTimestamp,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetFormattedTimestamp() string {
	if x != nil {
		return x.FormattedTimestamp
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The price value in minimum currency units, for example 10010, is 100$ and 10 penny
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Price) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId string `protobuf:"bytes,1,opt,name=ticketId,json=ticket_id,proto3" json:"ticketId,omitempty"`
	Status   Status `protobuf:"varint,2,opt,name=status,proto3,enum=cinema_orders_service.Status" json:"status,omitempty"`
	Price    *Price `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Place    *Place `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Ticket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Ticket) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PAYMENT_REQUIRED
}

func (x *Ticket) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Ticket) GetPlace() *Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ordering  Sort_Ordering `protobuf:"varint,1,opt,name=ordering,proto3,enum=cinema_orders_service.Sort_Ordering" json:"ordering,omitempty"`
	FieldName string        `protobuf:"bytes,2,opt,name=fieldName,json=field_name,proto3" json:"fieldName,omitempty"`
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Sort) GetOrdering() Sort_Ordering {
	if x != nil {
		return x.Ordering
	}
	return Sort_ASC
}

func (x *Sort) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// See fields names in OrderPreview, only no nested field name,
	// if not specified, sorting will be used with order DESC and sort_by_field=order_date
	Sort *Sort `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrdersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrdersRequest) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

type OrderPreview struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string     `protobuf:"bytes,1,opt,name=orderId,json=order_id,proto3" json:"orderId,omitempty"`
	OrderDate   *Timestamp `protobuf:"bytes,2,opt,name=orderDate,json=order_date,proto3" json:"orderDate,omitempty"`
	TotalPrice  *Price     `protobuf:"bytes,3,opt,name=totalPrice,json=total_price,proto3" json:"totalPrice,omitempty"`
	ScreeningId int64      `protobuf:"varint,4,opt,name=screeningId,json=screening_id,proto3" json:"screeningId,omitempty"`
}

func (x *OrderPreview) Reset() {
	*x = OrderPreview{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPreview) ProtoMessage() {}

func (x *OrderPreview) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPreview.ProtoReflect.Descriptor instead.
func (*OrderPreview) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *OrderPreview) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPreview) GetOrderDate() *Timestamp {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *OrderPreview) GetTotalPrice() *Price {
	if x != nil {
		return x.TotalPrice
	}
	return nil
}

func (x *OrderPreview) GetScreeningId() int64 {
	if x != nil {
		return x.ScreeningId
	}
	return 0
}

type OrdersPreviews struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*OrderPreview `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *OrdersPreviews) Reset() {
	*x = OrdersPreviews{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdersPreviews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersPreviews) ProtoMessage() {}

func (x *OrdersPreviews) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersPreviews.ProtoReflect.Descriptor instead.
func (*OrdersPreviews) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *OrdersPreviews) GetOrders() []*OrderPreview {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,json=order_id,proto3" json:"orderId,omitempty"`
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tickets     []*Ticket  `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	OrderDate   *Timestamp `protobuf:"bytes,2,opt,name=orderDate,json=order_date,proto3" json:"orderDate,omitempty"`
	ScreeningId int64      `protobuf:"varint,3,opt,name=screeningId,json=screening_id,proto3" json:"screeningId,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Order) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *Order) GetOrderDate() *Timestamp {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *Order) GetScreeningId() int64 {
	if x != nil {
		return x.ScreeningId
	}
	return 0
}

type ReservePlacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreeningId int64 `protobuf:"varint,1,opt,name=screeningId,json=screening_id,proto3" json:"screeningId,omitempty"`
	// The number of places must bigger than 0 and less than or equal to 5.
	Places []*Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *ReservePlacesRequest) Reset() {
	*x = ReservePlacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservePlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePlacesRequest) ProtoMessage() {}

func (x *ReservePlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePlacesRequest.ProtoReflect.Descriptor instead.
func (*ReservePlacesRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ReservePlacesRequest) GetScreeningId() int64 {
	if x != nil {
		return x.ScreeningId
	}
	return 0
}

func (x *ReservePlacesRequest) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type ReservePlacesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReserveId string `protobuf:"bytes,1,opt,name=reserveId,json=reserve_id,proto3" json:"reserveId,omitempty"`
	// The payment time of the order is in minutes, after this time the reserve is canceled.
	TimeToPay int32 `protobuf:"varint,2,opt,name=timeToPay,json=time_to_pay,proto3" json:"timeToPay,omitempty"`
}

func (x *ReservePlacesResponse) Reset() {
	*x = ReservePlacesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservePlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePlacesResponse) ProtoMessage() {}

func (x *ReservePlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePlacesResponse.ProtoReflect.Descriptor instead.
func (*ReservePlacesResponse) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ReservePlacesResponse) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

func (x *ReservePlacesResponse) GetTimeToPay() int32 {
	if x != nil {
		return x.TimeToPay
	}
	return 0
}

type ProcessOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReserveId string `protobuf:"bytes,1,opt,name=reserveId,json=reserve_id,proto3" json:"reserveId,omitempty"`
}

func (x *ProcessOrderRequest) Reset() {
	*x = ProcessOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrderRequest) ProtoMessage() {}

func (x *ProcessOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrderRequest.ProtoReflect.Descriptor instead.
func (*ProcessOrderRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessOrderRequest) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type GetScreeningsOccupiedPlacesCountsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for multiple values use ',' separator
	ScreeningsIds string `protobuf:"bytes,1,opt,name=screeningsIds,json=screenings_ids,proto3" json:"screeningsIds,omitempty"`
}

func (x *GetScreeningsOccupiedPlacesCountsRequest) Reset() {
	*x = GetScreeningsOccupiedPlacesCountsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScreeningsOccupiedPlacesCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreeningsOccupiedPlacesCountsRequest) ProtoMessage() {}

func (x *GetScreeningsOccupiedPlacesCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreeningsOccupiedPlacesCountsRequest.ProtoReflect.Descriptor instead.
func (*GetScreeningsOccupiedPlacesCountsRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetScreeningsOccupiedPlacesCountsRequest) GetScreeningsIds() string {
	if x != nil {
		return x.ScreeningsIds
	}
	return ""
}

type ScreeningsOccupiedPlacesCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreeningsOccupiedPlacesCount map[int64]uint32 `protobuf:"bytes,1,rep,name=screeningsOccupiedPlacesCount,json=screenings_occupied_places_count,proto3" json:"screeningsOccupiedPlacesCount,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *ScreeningsOccupiedPlacesCount) Reset() {
	*x = ScreeningsOccupiedPlacesCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreeningsOccupiedPlacesCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningsOccupiedPlacesCount) ProtoMessage() {}

func (x *ScreeningsOccupiedPlacesCount) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningsOccupiedPlacesCount.ProtoReflect.Descriptor instead.
func (*ScreeningsOccupiedPlacesCount) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ScreeningsOccupiedPlacesCount) GetScreeningsOccupiedPlacesCount() map[int64]uint32 {
	if x != nil {
		return x.ScreeningsOccupiedPlacesCount
	}
	return nil
}

type ProcessOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentUrl string `protobuf:"bytes,1,opt,name=paymentUrl,json=payment_url,proto3" json:"paymentUrl,omitempty"`
}

func (x *ProcessOrderResponse) Reset() {
	*x = ProcessOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrderResponse) ProtoMessage() {}

func (x *ProcessOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrderResponse.ProtoReflect.Descriptor instead.
func (*ProcessOrderResponse) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessOrderResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type GetOccupiedPlacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreeningId int64 `protobuf:"varint,1,opt,name=screeningId,json=screening_id,proto3" json:"screeningId,omitempty"`
}

func (x *GetOccupiedPlacesRequest) Reset() {
	*x = GetOccupiedPlacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOccupiedPlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOccupiedPlacesRequest) ProtoMessage() {}

func (x *GetOccupiedPlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOccupiedPlacesRequest.ProtoReflect.Descriptor instead.
func (*GetOccupiedPlacesRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *GetOccupiedPlacesRequest) GetScreeningId() int64 {
	if x != nil {
		return x.ScreeningId
	}
	return 0
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReserveId string `protobuf:"bytes,1,opt,name=reserveId,json=reserve_id,proto3" json:"reserveId,omitempty"`
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *CancelReservationRequest) GetReserveId() string {
	if x != nil {
		return x.ReserveId
	}
	return ""
}

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row  int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Seat int32 `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *Place) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Place) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

type Places struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *Places) Reset() {
	*x = Places{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Places) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Places) ProtoMessage() {}

func (x *Places) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Places.ProtoReflect.Descriptor instead.
func (*Places) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *Places) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type RefundOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,json=order_id,proto3" json:"orderId,omitempty"`
	// For a full refund, leave this field blank.
	ItemsIds []string `protobuf:"bytes,2,rep,name=itemsIds,json=items_ids,proto3" json:"itemsIds,omitempty"`
}

func (x *RefundOrderRequest) Reset() {
	*x = RefundOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderRequest) ProtoMessage() {}

func (x *RefundOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_orders_service_v1_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderRequest.ProtoReflect.Descriptor instead.
func (*RefundOrderRequest) Descriptor() ([]byte, []int) {
	return file_cinema_orders_service_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *RefundOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RefundOrderRequest) GetItemsIds() []string {
	if x != nil {
		return x.ItemsIds
	}
	return nil
}

var File_cinema_orders_service_v1_messages_proto protoreflect.FileDescriptor

var file_cinema_orders_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x3c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2f, 0x0a,
	0x12, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x1d,
	0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc4, 0x01,
	0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x32, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x40, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x24, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x1d, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d,
	0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53,
	0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x22, 0x7b, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x22, 0xcc, 0x01, 0x0a, 0x0c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x19, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x0e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x37, 0x0a, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x22, 0x6f, 0x0a,
	0x14, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x56,
	0x0a, 0x15, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f,
	0x50, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x74, 0x6f, 0x5f, 0x70, 0x61, 0x79, 0x22, 0x34, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x28,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x63, 0x63,
	0x75, 0x70, 0x69, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22,
	0x94, 0x02, 0x0a, 0x1d, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x63,
	0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0xa0, 0x01, 0x0a, 0x1d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73,
	0x4f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x57, 0x2e, 0x63, 0x69, 0x6e, 0x65,
	0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x63, 0x63, 0x75,
	0x70, 0x69, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x69,
	0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x20, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6f,
	0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x50, 0x0a, 0x22, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e,
	0x67, 0x73, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x37, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x22,
	0x3d, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0b, 0x73,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x22, 0x39,
	0x0a, 0x18, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x05, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x22, 0x3e, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x12, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x2a, 0x64, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x59, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x49, 0x52, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x49, 0x44, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x5f, 0x41, 0x57, 0x41, 0x49, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x45, 0x46, 0x55, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x05, 0x42, 0x21, 0x5a, 0x1f,
	0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cinema_orders_service_v1_messages_proto_rawDescOnce sync.Once
	file_cinema_orders_service_v1_messages_proto_rawDescData = file_cinema_orders_service_v1_messages_proto_rawDesc
)

func file_cinema_orders_service_v1_messages_proto_rawDescGZIP() []byte {
	file_cinema_orders_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_cinema_orders_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cinema_orders_service_v1_messages_proto_rawDescData)
	})
	return file_cinema_orders_service_v1_messages_proto_rawDescData
}

var file_cinema_orders_service_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cinema_orders_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_cinema_orders_service_v1_messages_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: cinema_orders_service.Status
	(Sort_Ordering)(0),            // 1: cinema_orders_service.Sort.Ordering
	(*Timestamp)(nil),             // 2: cinema_orders_service.Timestamp
	(*Price)(nil),                 // 3: cinema_orders_service.Price
	(*Ticket)(nil),                // 4: cinema_orders_service.Ticket
	(*Sort)(nil),                  // 5: cinema_orders_service.Sort
	(*GetOrdersRequest)(nil),      // 6: cinema_orders_service.GetOrdersRequest
	(*OrderPreview)(nil),          // 7: cinema_orders_service.OrderPreview
	(*OrdersPreviews)(nil),        // 8: cinema_orders_service.OrdersPreviews
	(*GetOrderRequest)(nil),       // 9: cinema_orders_service.GetOrderRequest
	(*Order)(nil),                 // 10: cinema_orders_service.Order
	(*ReservePlacesRequest)(nil),  // 11: cinema_orders_service.ReservePlacesRequest
	(*ReservePlacesResponse)(nil), // 12: cinema_orders_service.ReservePlacesResponse
	(*ProcessOrderRequest)(nil),   // 13: cinema_orders_service.ProcessOrderRequest
	(*GetScreeningsOccupiedPlacesCountsRequest)(nil), // 14: cinema_orders_service.GetScreeningsOccupiedPlacesCountsRequest
	(*ScreeningsOccupiedPlacesCount)(nil),            // 15: cinema_orders_service.ScreeningsOccupiedPlacesCount
	(*ProcessOrderResponse)(nil),                     // 16: cinema_orders_service.ProcessOrderResponse
	(*GetOccupiedPlacesRequest)(nil),                 // 17: cinema_orders_service.GetOccupiedPlacesRequest
	(*CancelReservationRequest)(nil),                 // 18: cinema_orders_service.CancelReservationRequest
	(*Place)(nil),                                    // 19: cinema_orders_service.Place
	(*Places)(nil),                                   // 20: cinema_orders_service.Places
	(*RefundOrderRequest)(nil),                       // 21: cinema_orders_service.RefundOrderRequest
	nil,                                              // 22: cinema_orders_service.ScreeningsOccupiedPlacesCount.ScreeningsOccupiedPlacesCountEntry
}
var file_cinema_orders_service_v1_messages_proto_depIdxs = []int32{
	0,  // 0: cinema_orders_service.Ticket.status:type_name -> cinema_orders_service.Status
	3,  // 1: cinema_orders_service.Ticket.price:type_name -> cinema_orders_service.Price
	19, // 2: cinema_orders_service.Ticket.place:type_name -> cinema_orders_service.Place
	1,  // 3: cinema_orders_service.Sort.ordering:type_name -> cinema_orders_service.Sort.Ordering
	5,  // 4: cinema_orders_service.GetOrdersRequest.sort:type_name -> cinema_orders_service.Sort
	2,  // 5: cinema_orders_service.OrderPreview.orderDate:type_name -> cinema_orders_service.Timestamp
	3,  // 6: cinema_orders_service.OrderPreview.totalPrice:type_name -> cinema_orders_service.Price
	7,  // 7: cinema_orders_service.OrdersPreviews.orders:type_name -> cinema_orders_service.OrderPreview
	4,  // 8: cinema_orders_service.Order.tickets:type_name -> cinema_orders_service.Ticket
	2,  // 9: cinema_orders_service.Order.orderDate:type_name -> cinema_orders_service.Timestamp
	19, // 10: cinema_orders_service.ReservePlacesRequest.places:type_name -> cinema_orders_service.Place
	22, // 11: cinema_orders_service.ScreeningsOccupiedPlacesCount.screeningsOccupiedPlacesCount:type_name -> cinema_orders_service.ScreeningsOccupiedPlacesCount.ScreeningsOccupiedPlacesCountEntry
	19, // 12: cinema_orders_service.Places.places:type_name -> cinema_orders_service.Place
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cinema_orders_service_v1_messages_proto_init() }
func file_cinema_orders_service_v1_messages_proto_init() {
	if File_cinema_orders_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cinema_orders_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPreview); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdersPreviews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservePlacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservePlacesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScreeningsOccupiedPlacesCountsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreeningsOccupiedPlacesCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOccupiedPlacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelReservationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Places); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_orders_service_v1_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cinema_orders_service_v1_messages_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cinema_orders_service_v1_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cinema_orders_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_cinema_orders_service_v1_messages_proto_depIdxs,
		EnumInfos:         file_cinema_orders_service_v1_messages_proto_enumTypes,
		MessageInfos:      file_cinema_orders_service_v1_messages_proto_msgTypes,
	}.Build()
	File_cinema_orders_service_v1_messages_proto = out.File
	file_cinema_orders_service_v1_messages_proto_rawDesc = nil
	file_cinema_orders_service_v1_messages_proto_goTypes = nil
	file_cinema_orders_service_v1_messages_proto_depIdxs = nil
}
